### Laelaps laelaps_control/GetImuAlt service.
#
# Get the current Inertia Measurement Unit data.
#
# Reads are deep retrievals of the data directly from the sensor. Gets retrieve
# the latest read sensor data stored in shadow values by a background thread.
#

string  name  # Name of IMU: One of: imu
---
ImuAlt  imu   # IMU data.
