#! /usr/bin/env python

###############################################################################
#
# Package:   RoadNarrows Robotics Laelaps Robotic Mobile Platform ROS Package
#
# Link:      https://github.com/roadnarrows-robotics/laelaps
#
# ROS Node:  laelaps_panel
#
# File: laelaps_panel
#
## \file 
##
## $LastChangedDate: 2012-12-06 16:33:18 -0700 (Thu, 06 Dec 2012) $
## $Rev: 330 $
##
## \brief Graphical panel to interface with the laelaps_control node.
##
## \author Robin Knight (robin.knight@roadnarrows.com)
##  
## \par Copyright:
##   (C) 2015-2016.  RoadNarrows LLC.\n
##   (http://www.roadnarrows.com)\n
##   All Rights Reserved
##
# @EulaBegin@
# @EulaEnd@
#
###############################################################################

import sys
import os
import time
import math
import getopt

from Tkinter import *
from Tkconstants import *
from tkFileDialog import *
import tkFont

import random

import roslib; roslib.load_manifest('laelaps_control')
import rospy

from industrial_msgs.msg import RobotMode
from industrial_msgs.msg import TriState

from laelaps_control.msg import Dynamics            # subscribe
from laelaps_control.srv import EStop               # service
from laelaps_control.srv import Freeze              # service
from laelaps_control.srv import GetProductInfo      # service
from laelaps_control.srv import Release             # service
from laelaps_control.msg import MotorCtlrHealth     # message
from laelaps_control.msg import MotorHealth         # message
from laelaps_control.srv import ResetEStop          # service
from laelaps_control.msg import RobotStatusExtended # subscribe
from laelaps_control.msg import Velocity            # publish

from laelaps_control.Utils import *
from laelaps_control.PanelConfig import *
from laelaps_control.Gauge import *
from laelaps_control.AboutDlg import AboutDlg
from laelaps_control.WarnDlg import WarnDlg
from laelaps_control.AlarmsWin import AlarmsWin


# ------------------------------------------------------------------------------
# Globals
# ------------------------------------------------------------------------------

## \brief Application version. Update as needed. 
appVersion = '1.2.0'

## \brief Additional image search paths.
imagePath = [
  "/prj/share/appkit/images",
  "/usr/local/share/appkit/images"
]

## \brief Common foreground colors.
fgColors = {
  'normal':   'black',
  'ok':       '#008800',
  'focus':    '#0000aa',
  'warning':  '#aa6600',
  'error':    '#cc0000'
}


# ------------------------------------------------------------------------------
# Class window
# ------------------------------------------------------------------------------

##
## \brief Window class supporting application.
##
class window(Frame):
  #
  ## \brief Constructor.
  ##
  ## \param master  Window parent master widget.
  ## \param cnf     Configuration dictionary.
  ## \param kw      Keyword options.
  #
  def __init__(self, master=None, cnf={}, **kw):
    # intialize window data
    kw = self.initData(kw)

    # publish speed command
    self.m_pub_velocities = \
        rospy.Publisher("laelaps_control/cmd_wheel_velocities",
        Velocity, queue_size=2)

    self.m_imageLoader = ImageLoader(py_pkg='laelaps_control.images',
                                      image_paths=imagePath)

    Frame.__init__(self, master=master, cnf=cnf, **kw)
    self.master.title("Laelaps Control Panel")

    self.m_icons['app_icon'] = \
                    self.m_imageLoader.loadImage("icons/LaelapsPanelIcon.png")
    self.master.tk.call('wm', 'iconphoto', self.master._w,
        self.m_icons['app_icon'])

    # craete and show widgets
    self.createWidgets()

    self.grid(row=0, column=0, padx=5, pady=5)

  #
  ## \brief Initialize class state data.
  ##
  ## Any keywords for this application specific window that are not supported 
  ## by the Frame Tkinter class must be removed.
  ##
  ## \param kw      Keyword options.
  ##
  ## \return Modified keywords sans this specific class.
  #
  def initData(self, kw):
    self.m_debug          = False # default debug level
    self.m_config         = ConfigDlg.ConfigDft
    self.m_icons          = {}    # must keep loaded icons referenced
    self.m_wBttn          = {}    # button widgets
    self.m_keysFewMoves   = []    # gui button keys depending on calibration
    self.m_keysNoMoves    = []    # gui button keys depending on robot mode
    self.m_robotState     = {}    # robot state widgets, variables, and values
    self.m_subsysState    = {}    # subsystems state widgets, variables, values
    self.m_alarmsWin      = None  # alarms sub-panel

    if kw.has_key('config'):
      self.m_config = kw['config']
      del kw['config']
    if kw.has_key('pub_joint_move_cb'):
      self.cbMoveRobot = kw['pub_joint_move_cb']
      del kw['pub_joint_move_cb']
    if kw.has_key('debug'):
      self.m_debug = kw['debug']
      del kw['debug']

    # variables only used for debugging
    if self.m_debug:
      self.m_dbgSeq         = 0                     # debug sequence number
      self.m_dbgStatusMsg   = RobotStatusExtended() # robot status message
      self.m_dbgDynamicsMsg = Dynamics()            # robot dynamics message

    return kw

  #
  ## \brief Create gui widgets with supporting data and show.
  #
  def createWidgets(self):
    self.createHeading()
    self.createLeftButtons()
    self.createCenterPanel()
    self.createRightButtons()
    self.createStatusBar()
    self.updateButtonState(self.m_keysFewMoves, 'disabled')

  #
  ## \brief Create top gui heading.
  #
  def createHeading(self):
    # rn logo
    w = Label(self)
    self.m_icons['rn_logo'] = self.m_imageLoader.loadImage("RNLogo48.png");
    if self.m_icons['rn_logo']:
      w['image'] = self.m_icons['rn_logo']
    else:
      w['text'] = 'rn'
      w['anchor'] = W
      w['width'] = 5
    w.grid(row=0, column=0, sticky=W)
    
    # top heading
    w = Label(self)
    w['font']   = ('Helvetica', 16)
    w['text']   = 'Laelaps Control Panel'
    w['anchor'] = CENTER
    w.grid(row=0, column=1, sticky=E+W)

    # laelaps logo
    w = Label(self)
    self.m_icons['laelaps_logo'] = \
        self.m_imageLoader.loadImage("icons/icon_laelaps_logo.png");
    if self.m_icons['laelaps_logo']:
      w['image'] = self.m_icons['laelaps_logo']
      w['anchor'] = E
    else:
      w['text'] = 'laelaps'
      w['anchor'] = E
      w['width'] = 5
    w.grid(row=0, column=2, sticky=E)
    
  #
  ## \brief Create gui left hand side buttons.
  #
  def createLeftButtons(self):
    wframe = Frame(self)
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=1, column=0, padx=1, pady=3, sticky=N+W+E)

    row = 0

    # move foward
    w = self.createButton(wframe, "Forward", "icons/icon_bot_forward.png",
                            self.cbMoveForward)
    w.grid(row=row, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('forward')

    # move backward
    row += 1
    w = self.createButton(wframe, "Back", "icons/icon_bot_back.png",
                            self.cbMoveBackward)
    w.grid(row=row, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('back')

    # spin left
    row += 1
    w = self.createButton(wframe, "Spin\nLeft", "icons/icon_bot_spin_left.png",
                            self.cbSpinLeft)
    w.grid(row=row, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('spin_left')

    # spin right
    row += 1
    w = self.createButton(wframe, "Spin\nRight",
                            "icons/icon_bot_spin_right.png",
                            self.cbSpinRight)
    w.grid(row=row, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('spin_right')

    # stop 
    row += 1
    w = self.createButton(wframe, "Stop",
                                  "icons/icon_bot_brake.png",
                                  self.cbStop)
    w.grid(row=row, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('stop')

    ## specify move
    #w = self.createButton(wframe, "Specify\nMove",
    #                              "icons/icon_bot_in_motion.png",
    #                              self.specifyMove)
    #w.grid(row=row, column=0, sticky=N+E+W)
    #self.m_keysNoMoves.append('specify_move')

    # debug 
    if self.m_debug:
      row += 1
      w = self.createButton(wframe, "Test", "", self.cbDebug)
      w.grid(row=row, column=0, sticky=N+E+W)

  #
  ## \brief Create robot status and joint state center panel.
  #
  def createCenterPanel(self):
    self.m_wPanelFrame = Frame(self)
    self.m_wPanelFrame['borderwidth'] = 2
    self.m_wPanelFrame['relief'] = 'ridge'
    self.m_wPanelFrame.grid(row=1, column=1, padx=1, pady=3, sticky=N+W+E)

    self.createDashboard(self.m_wPanelFrame, 0)
    self.createSubsystems(self.m_wPanelFrame, 1)

  def createDashboard(self, parent, row):
    wframe = LabelFrame(parent, text='Dashboard')
    wframe['font'] =('Helvetica', 12)
    wframe['fg'] = fgColors['focus']
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=row, column=0, padx=1, pady=3, sticky=N+W+E)

    #
    # Left gauge cluster
    #
    subframe = Frame(wframe, relief="flat")
    subframe.grid(row=0, column=0, sticky=N)
  
    w = Indicator(subframe, gauge_label='Auto')
    w.grid(row=0, column=0)
    self.m_robotState['mode'] = {
        'raw_val':  RobotMode.UNKNOWN,
        'var':      None,
        'widget':   w,
        'type':     'indicator'}
  
    w = Indicator(subframe, gauge_label='Motors')
    w.grid(row=0, column=1)
    self.m_robotState['motors'] = {
        'raw_val':  TriState.UNKNOWN,
        'var':      None,
        'widget':   w,
        'type':     'indicator'}
  
    w = Indicator(subframe, gauge_label='Moving')
    w.grid(row=0, column=2)
    self.m_robotState['moving'] = {
        'raw_val':  TriState.UNKNOWN,
        'var':      None,
        'widget':   w,
        'type':     'indicator'}
  
    w = Canvas(subframe, width=20, height=50, borderwidth=0)
    w.grid(row=1, column=0, padx=0, ipadx=0)

    subsubframe = Frame(subframe, relief="flat")
    subsubframe.grid(row=2, column=0, columnspan=3, padx=0, ipadx=0, sticky=W)
  
    w = Button(subsubframe, text='reset', bg="#333333", fg="#ffffff",
        padx=1, pady=1, command=self.cbResetTripMeter)
    w.grid(row=0, column=0, padx=0, ipadx=0, sticky=W)
    self.m_robotState['reset_trip_meter'] = {
        'raw_val':  0,
        'var':      None,
        'widget':   w,
        'type':     'button'}
  
    w = Counter(subsubframe, gauge_size=(17, 25),
        gauge_val_min=0.0, gauge_val_max=1000.0, gauge_res=0.01, padx=0,
        gauge_label="trip", relief="flat", borderwidth=3)
    w.grid(row=0, column=1, columnspan=3, padx=0, sticky=S+E)
    self.m_robotState['trip_meter'] = {
        'raw_val':  0.0,        # offset from odometer
        'var':      None,
        'widget':   w,
        'type':     'counter'}

    #
    # Center gauge cluster
    #
    w = Dial(wframe,
        gauge_val_min=0.0, gauge_val_max=250.0, gauge_val_home=0.0,
        gauge_size=150, gauge_res=0.5, gauge_label="watts",
        gauge_show_val=True, gauge_moving_win=4,
        gauge_dial_image="GaugeDialGreenRed.png",
        gauge_needle_image="GaugeNeedleWhite.png",
        gauge_text_color="#ffffff")
    w.grid(row=0, column=1);
    self.m_robotState['watts'] = {
        'raw_val':  0.0,
        'var':      None,
        'widget':   w,
        'type':     'dial'}
  
    w = Dial(wframe,
        gauge_val_min=0.0, gauge_val_max=4.5, gauge_val_home=0,
        gauge_size=150, gauge_res=0.5, gauge_label="m/s",
        gauge_show_val=True, gauge_moving_win=4,
        gauge_dial_image="GaugeDialGreenRed.png",
        gauge_needle_image="GaugeNeedleWhite.png",
        gauge_text_color="#ffffff")
    w.grid(row=0, column=2);
    self.m_robotState['velocity'] = {
        'raw_val':  0.0,
        'var':      None,
        'widget':   w,
        'type':     'dial'}
  
    w = Dial(wframe,
        gauge_val_min=0.0, gauge_val_max=100.0, gauge_val_home=0,
        gauge_size=100, gauge_res=0.5, gauge_label=u"C\u00b0",
        gauge_show_val=True,
        gauge_dial_image="GaugeDialBlueRed.png",
        gauge_needle_image="GaugeNeedleWhite.png",
        gauge_text_color="#ffffff")
    w.grid(row=0, column=3, sticky=N)
    self.m_robotState['temp'] = {
        'raw_val':  0.0,
        'var':      None,
        'widget':   w,
        'type':     'dial'}
  
    #
    # Right gauge cluster
    #
    subframe = Frame(wframe, relief="flat")
    subframe.grid(row=0, column=4, sticky=N)
  
    w = Indicator(subframe, gauge_label='Alarms')
    w.grid(row=0, column=0)
    self.m_robotState['alarms'] = {
        'raw_val':  TriState.UNKNOWN,
        'var':      None,
        'widget':   w,
        'type':     'indicator'}
  
    w = Indicator(subframe, gauge_label='EStop')
    w.grid(row=0, column=1)
    self.m_robotState['estop'] = {
        'raw_val':  TriState.UNKNOWN,
        'var':      None,
        'widget':   w,
        'type':     'indicator'}
  
    w = Battery(subframe, gauge_rot=90, gauge_size=(100, 48))
    w.grid(row=0, column=2)
    self.m_robotState['battery'] = {
        'raw_val':  (0.0, False),
        'var':      None,
        'widget':   w,
        'type':     'battery'}

    w = Canvas(subframe, width=20, height=50, borderwidth=0)
    w.grid(row=1, column=0, padx=0, ipadx=0)

    w = Counter(subframe, gauge_size=(20, 30),
        gauge_val_min=0.0, gauge_val_max=1000000.0, gauge_res=0.01,
        gauge_label="m", relief="flat", borderwidth=3)
    w.grid(row=2, column=0, columnspan=3, padx=0, sticky=S+W)
    self.m_robotState['odometer'] = {
        'raw_val':  0.0,
        'var':      None,
        'widget':   w,
        'type':     'counter'}
  
  #
  ## \brief Create subsystem state lower center panel headers.
  ##
  ## \param parent  Parent widget
  ## \param row     Row in parent widget.
  #
  def createSubsystems(self, parent, row):
    wframe = LabelFrame(parent, text='Robot Subsystems')
    wframe['font'] =('Helvetica', 12)
    wframe['fg'] = fgColors['focus']
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=row, column=0, padx=1, pady=3, sticky=N+W+E)
    self.m_wJointStateFrame = wframe

    helv  = tkFont.Font(family="Helvetica",size=10,weight="bold")
    padx  = 10
    pady  = 3
    row   = 0
    col   = 0

    # Center top-down view
    self.m_icons['laelaps_top_down'] = \
        self.m_imageLoader.loadImage("LaelapsTopDown300.png")

    w = Canvas(wframe, width=300, height=300)
    w.grid(row=0, column=1, rowspan=2, padx=0, pady=0, sticky=E+W)

    if self.m_icons['laelaps_top_down'] is not None:
      w.create_image(150, 150, image=self.m_icons['laelaps_top_down'])

    padx = 15

    self.m_subsysState['powertrain'] = {}

    # Left-Front motor/wheel/tire
    wsubframe = Frame(wframe);
    wsubframe['borderwidth'] = 0
    wsubframe['relief'] = 'flat'
    wsubframe['height'] = 190
    wsubframe.grid(row=0, column=0, padx=padx, pady=0, sticky=N+W+E)
    wsubframe.grid_propagate(0)

    self.createPowertrainSubpanel(wsubframe, 'left_front', True)

    # Left-Rear motor/wheel/tire
    wsubframe = Frame(wframe);
    wsubframe['borderwidth'] = 0
    wsubframe['relief'] = 'flat'
    wsubframe.grid(row=1, column=0, padx=padx, pady=0, sticky=N+W+E)

    self.createPowertrainSubpanel(wsubframe, 'left_rear', True)

    # Right-Front motor/wheel/tire
    wsubframe = Frame(wframe);
    wsubframe['borderwidth'] = 0
    wsubframe['relief'] = 'flat'
    wsubframe.grid(row=0, column=2, padx=padx, pady=0, sticky=N+W+E)

    self.createPowertrainSubpanel(wsubframe, 'right_front', False)

    # Right-Rear motor/wheel/tire
    wsubframe = Frame(wframe);
    wsubframe['borderwidth'] = 0
    wsubframe['relief'] = 'flat'
    wsubframe.grid(row=1, column=2, padx=padx, pady=0, sticky=N+W+E)

    self.createPowertrainSubpanel(wsubframe, 'right_rear', False)

  #
  ## \brief Create joint state lower center panel state.
  ##
  ## \param wframe    Frame to add labels and fields.
  ## \param ptName    Powertrain name (and key).
  ## \param onLeft    Labeling is [not] on the left.
  #
  def createPowertrainSubpanel(self, wframe, ptName, onLeft):
    d = {}

    w = Dial(wframe,
      gauge_val_min=0.0, gauge_val_max=60.0, gauge_val_home=0.0,
      gauge_size=100, gauge_res=0.5, gauge_label="watts",
      gauge_show_val=True, gauge_moving_win=4,
      gauge_dial_image="GaugeDialGreenRed.png",
      gauge_needle_image="GaugeNeedleWhite.png",
      gauge_text_color="#ffffff")
    w.grid(row=0, column=0);
    d['watts'] = {
        'raw_val':  0.0,
        'var':      None,
        'widget':   w,
        'type':     'dial'}

    w = Dial(wframe,
      gauge_val_min=-12000, gauge_val_max=12000, gauge_val_home=0,
      gauge_size=100, gauge_res=10, gauge_label="qpps",
      gauge_show_val=True, gauge_val_fmt="%.0f", gauge_moving_win=4,
      gauge_dial_image="GaugeDialRedGreenRed.png",
      gauge_needle_image="GaugeNeedleWhite.png",
      gauge_text_color="#ffffff")
    w.grid(row=0, column=1);
    d['qpps'] = {
        'raw_val':  0.0,
        'var':      None,
        'widget':   w,
        'type':     'dial'}

    w = Counter(wframe, gauge_size=(15, 22),
      gauge_val_min=-5000000000, gauge_val_max=5000000000,
      gauge_val_home=0,
      gauge_label="p", relief="flat", borderwidth=3)
      #relief='ridge', borderwidth=1, bg="#000000")
    w.grid(row=1, column=0, columnspan=2);
    d['pulses'] = {
        'raw_val':  0,
        'var':      None,
        'widget':   w,
        'type':     'counter'}

    self.m_subsysState['powertrain'][ptName] = d

  #
  ## \brief Create gui right hand side buttons.
  #
  def createRightButtons(self):
    wframe = Frame(self)
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=1, column=2, padx=1, pady=3, sticky=N+W+E)

    row = 0;

    # estop
    w = self.createButton(wframe, "ESTOP", "icons/icon_estop.png", self.cbEStop,
                                  fg='red')
    w.grid(row=row, column=0, sticky=N+E+W)
    self.m_icons['estop_reset'] = \
        self.m_imageLoader.loadImage("icons/icon_estop_reset.png")

    # release
    row += 1
    w = self.createButton(wframe, "Neutral",
                                  "icons/icon_pause.png", self.cbRelease)
    w.grid(row=row, column=0, sticky=N+E+W)
    self.m_keysNoMoves.append('neutral')

    # alarms
    row += 1
    w = self.createButton(wframe, "Alarms",
                                  "icons/icon_alarm.png", self.cbAlarms)
    w.grid(row=row, column=0, sticky=N+E+W)

    # settings
    row += 1
    w = self.createButton(wframe, "Settings",
                                 "icons/icon_settings.png", self.cbSettings)
    w.grid(row=row, column=0, sticky=N+E+W)

    # info
    row += 1
    w = self.createButton(wframe, "About",
                                  "icons/icon_info.png", self.cbAbout)
    w.grid(row=row, column=0, sticky=N+E+W)

    # quit
    row += 1
    w = self.createButton(wframe, "Quit", "icons/icon_exit.png", self.destroy,
                                  fg='red')
    w.grid(row=row, column=0, sticky=N+E+W)

  #
  ## \brief Create gui status bar at bottom of gui window.
  #
  def createStatusBar(self):
    wframe = Frame(self)
    wframe['borderwidth'] = 2
    wframe['relief'] = 'ridge'
    wframe.grid(row=2, column=0, columnspan=3, padx=1, pady=3, sticky=N+E+W+S)

    self.m_varStatus = StringVar()
    self.m_varStatus.set("")
    self.m_wStatusBar = Entry(wframe)
    self.m_wStatusBar['width']    = wframe['width']
    self.m_wStatusBar['relief']   = 'flat'
    self.m_wStatusBar['textvar']  = self.m_varStatus
    self.m_wStatusBar['fg']       = fgColors['normal']
    self.m_wStatusBar['state']    = 'readonly'
    self.m_wStatusBar.grid(row=0, column=0, padx=3, pady=3, sticky=N+E+W+S)

  #
  ## \brief Update button activation states.
  #
  def updateButtonState(self, keys, state):
    for key in keys:
      self.m_wBttn[key]['state'] = state

  #
  ## \brief Create button.
  ##
  ## \param parent    Parent widget.
  ## \param text      Button text.
  ## \param imagefile Image file name. None for no image.
  ## \param command   Callback for button push.
  ## \param fg        Foreground text color.
  ##
  ## \return Button widget.
  #
  def createButton(self, parent, text, imagefile, command, fg='black'):
    key = str.lower(text.replace("\n", "_"))
    self.m_icons[key] = self.m_imageLoader.loadImage(imagefile)
    w = Button(parent)
    w['text']     = text
    if self.m_icons[key]:
      w['image']    = self.m_icons[key]
      w['compound'] = LEFT
      w['padx']     = 0
      w['pady']     = 0
      w['anchor']   = W
      w['width']    = 105
    else:
      w['anchor']   = CENTER
      w['width']    = 10
    w['fg']       = fg
    w['command']  = command
    self.m_wBttn[key] = w
    return self.m_wBttn[key]

  #
  ## \brief Destroy window callback.
  #
  def destroy(self):
    self.cbStop()
    self.quit()

  #
  ## \brief Reset trip meter callback.
  #
  def cbResetTripMeter(self):
    key = 'odometer'
    od = self.m_robotState[key]['raw_val']
    key = 'trip_meter'
    self.m_robotState[key]['raw_val'] = od # offset
    self.m_robotState[key]['widget'].update(0.0)
    self.showInfo("Trip meter reset.")

  #
  ## \brief Move forward callback.
  #
  def cbMoveForward(self):
    self.showInfo("Moving forward.")
    cmd = Velocity()
    cmd.names = ['left_front', 'right_front', 'left_rear', 'right_rear']
    cmd.velocities = [20.0, 20.0, 20.0, 20.0]
    self.m_pub_velocities.publish(cmd)
  
  #
  ## \brief Move backward callback.
  #
  def cbMoveBackward(self):
    self.showInfo("Moving back.")
    cmd = Velocity()
    cmd.names = ['left_front', 'right_front', 'left_rear', 'right_rear']
    cmd.velocities = [-20.0, -20.0, -20.0, -20.0]
    self.m_pub_velocities.publish(cmd)
  
  #
  ## \brief Spin left callback.
  #
  def cbSpinLeft(self):
    self.showInfo("Spinning left.")
    cmd = Velocity()
    cmd.names = ['left_front', 'right_front', 'left_rear', 'right_rear']
    cmd.velocities = [-20.0,  20.0, -20.0, 20.0]
    self.m_pub_velocities.publish(cmd)
  
  #
  ## \brief Spin right callback.
  #
  def cbSpinRight(self):
    self.showInfo("Spinning right.")
    cmd = Velocity()
    cmd.names = ['left_front', 'right_front', 'left_rear', 'right_rear']
    cmd.velocities = [20.0, -20.0, 20.0, -20.0]
    self.m_pub_velocities.publish(cmd)
  
  #
  ## \brief Brake to stop callback.
  #
  def cbStop(self):
    try:
      rospy.wait_for_service("laelaps_control/stop", timeout=1)
    except rospy.ROSException, e:
      self.showError('Stop: ' + e.message + '.')
      return
    try:
      stop = rospy.ServiceProxy('laelaps_control/stop', Freeze)
      stop()
    except rospy.ServiceException, e:
      self.showError("Stop request failed: %s." % (e.message))
      return
    self.showInfo("Stopped.")
  
  #
  ## \brief Specify move button callback.
  #
  def specifyMove(self):
    pass
  
  #
  ## \brief (Reset) Emergency stop button callback.
  #
  def cbEStop(self):
    if self.m_robotState['estop']['raw_val'] != TriState.TRUE:
      self.showResetEStop()
      try:
        rospy.wait_for_service("laelaps_control/estop", timeout=1)
      except rospy.ROSException, e:
        self.showError('Emergency stop: ' + e.message + '.')
        self.showEStop()
        return
      try:
        estop = rospy.ServiceProxy('laelaps_control/estop', EStop)
        estop()
      except rospy.ServiceException, e:
        self.showError("Emergency stop request failed: %s." % (e.message))
        self.showEStop()
        return
      self.showError("Laelaps emergency stopped.")
    else:
      self.showEStop()
      try:
        rospy.wait_for_service("laelaps_control/reset_estop", timeout=1)
      except rospy.ROSException, e:
        self.showError('Reset emergency stop: ' + e.message + '.')
        self.showResetEStop()
        return
      try:
        reset_estop = rospy.ServiceProxy('laelaps_control/reset_estop',
                                          ResetEStop)
        reset_estop()
      except rospy.ServiceException, e:
        self.showError("Reset emergency stop request failed: %s." % (e.message))
        self.showResetEStop()
        return
      self.showInfo("Laelaps emergency stop has been reset.")
  
  #
  ## \brief Park laelaps button callback.
  #
  def cbFreeze(self):
    try:
      rospy.wait_for_service("laelaps_control/freeze", timeout=1)
    except rospy.ROSException, e:
      self.showError('Freeze: ' + e.message + '.')
      return
    try:
      freeze = rospy.ServiceProxy('laelaps_control/freeze', Freeze)
      freeze()
    except rospy.ServiceException, e:
      self.showError("Freeze request failed: %s." % (e.message))
      return
    self.showInfo("Motors fully braked.")

  #
  ## \brief Release laelaps button callback.
  #
  def cbRelease(self):
    try:
      rospy.wait_for_service("laelaps_control/release", timeout=1)
    except rospy.ROSException, e:
      self.showError('Release: ' + e.message + '.')
      return
    try:
      release = rospy.ServiceProxy('laelaps_control/release', Release)
      release()
    except rospy.ServiceException, e:
      self.showError("Release request failed: %s." % (e.message))
      return
    self.showInfo("Motors released.")

  #
  ## \brief Show alarms panel.
  #
  def cbAlarms(self):
    if self.m_alarmsWin is None:
      self.m_alarmsWin = AlarmsWin(self)
    elif not self.m_alarmsWin.m_isCreated:
      del self.m_alarmsWin
      self.m_alarmsWin = AlarmsWin(self)
    else:
      self.m_alarmsWin.lift()

  #
  ## \brief Show estop button.
  #
  def showEStop(self):
    self.m_wBttn['estop']['image'] = self.m_icons['estop']
    self.m_wBttn['estop']['text']   = "ESTOP"
    self.m_wBttn['estop']['fg']     = fgColors['error']
    self.update_idletasks()

  #
  ## \brief Show reset estop button.
  #
  def showResetEStop(self):
    self.m_wBttn['estop']['image']  = self.m_icons['estop_reset']
    self.m_wBttn['estop']['text']   = "Reset\nESTOP"
    self.m_wBttn['estop']['fg']     = fgColors['normal']
    self.update_idletasks()

  #
  ## \brief Clear alarms button callback.
  #
  def clearAlarms(self):
    try:
      rospy.wait_for_service("laelaps_control/clear_alarms", timeout=1)
    except rospy.ROSException, e:
      self.showError('Clear alarms: ' + e.message + '.')
      return
    try:
      clear_alarms = rospy.ServiceProxy('laelaps_control/clear_alarms',
                                          ClearAlarms)
      clear_alarms()
    except rospy.ServiceException, e:
      self.showError("Clear alarms request failed: %s." % (e.message))
      return
    self.showInfo("Alarms cleared.")
  
  #
  ## \brief Open settings dialog button callback.
  #
  def cbSettings(self):
    dlg = ConfigDlg(master=self, config=self.m_config)
    self.m_config = dlg.m_config
    if dlg.m_saved:
      self.showInfo("Configuration saved to %s" % (dlg.m_filename))
  
  #
  ## \brief Show about dialog button callback.
  #
  def cbAbout(self):
    prodInfo = None
    try:
      rospy.wait_for_service("laelaps_control/get_product_info", timeout=1)
    except rospy.ROSException, e:
      self.showError('Get product info: ' + e.message + '.')
    else:
      try:
        get_product_info = rospy.ServiceProxy(
                                          'laelaps_control/get_product_info',
                                          GetProductInfo)
        rsp = get_product_info()
        prodInfo = rsp.i
      except rospy.ServiceException, e:
        self.showError("Get product info request failed: %s." % (e.message))
    dlg = AboutDlg(master=self, info=prodInfo, app_ver=appVersion)
  
  def cbDebug(self):
    #
    # unknown state
    #
    if self.m_dbgSeq == 0:
      # Robot status message
      self.m_dbgStatusMsg.mode.val = RobotMode.UNKNOWN 
      self.m_dbgStatusMsg.e_stopped.val = TriState.UNKNOWN
      self.m_dbgStatusMsg.drives_powered.val = TriState.UNKNOWN
      self.m_dbgStatusMsg.motion_possible.val = TriState.UNKNOWN
      self.m_dbgStatusMsg.in_motion.val = TriState.UNKNOWN
      self.m_dbgStatusMsg.in_error.val = TriState.UNKNOWN
      self.m_dbgStatusMsg.battery = 0.0
      self.m_dbgStatusMsg.is_charging.val = TriState.UNKNOWN
      self.m_dbgStatusMsg.voltage = 0.0
      self.m_dbgStatusMsg.current = 0.0
      self.m_dbgStatusMsg.temp = 0.0
      self.m_dbgStatusMsg.aux_batt_en.val = TriState.UNKNOWN
      self.m_dbgStatusMsg.aux_5v_en.val = TriState.UNKNOWN

      # Robot dyanmics message
      self.m_dbgDynamicsMsg.robot_odometer = 0.0
      self.m_dbgDynamicsMsg.robot_pose.x = 0.0
      self.m_dbgDynamicsMsg.robot_pose.y = 0.0
      self.m_dbgDynamicsMsg.robot_pose.theta = 0.0
      self.m_dbgDynamicsMsg.robot_velocity = 0.0
      self.m_dbgDynamicsMsg.name = [
        'left_front', 'right_front', 'left_rear', 'right_rear']
      self.m_dbgDynamicsMsg.motor_encoder = [0, 0, 0, 0]
      self.m_dbgDynamicsMsg.motor_speed = [0, 0, 0, 0]
      self.m_dbgDynamicsMsg.motor_power_elec = [0.0, 0.0, 0.0, 0.0]

    #
    # typical start state
    #
    elif self.m_dbgSeq == 1:
      # Robot status message
      self.m_dbgStatusMsg.mode.val = RobotMode.AUTO 
      self.m_dbgStatusMsg.e_stopped.val = TriState.FALSE
      self.m_dbgStatusMsg.drives_powered.val = TriState.TRUE
      self.m_dbgStatusMsg.motion_possible.val = TriState.TRUE
      self.m_dbgStatusMsg.in_motion.val = TriState.FALSE
      self.m_dbgStatusMsg.in_error.val = TriState.FALSE
      self.m_dbgStatusMsg.battery = 72.3
      self.m_dbgStatusMsg.is_charging.val = TriState.FALSE
      self.m_dbgStatusMsg.voltage = 11.2
      self.m_dbgStatusMsg.current = 12.5
      self.m_dbgStatusMsg.temp = 35.9
      self.m_dbgStatusMsg.aux_batt_en.val = TriState.TRUE
      self.m_dbgStatusMsg.aux_5v_en.val = TriState.TRUE

    #
    # operational state
    #
    else:
      # Robot status message
      # mode
      self.m_dbgStatusMsg.mode.val = random.choice([RobotMode.AUTO,
                                                    RobotMode.MANUAL])
      # not in estop
      if random.random() < 0.95:
        self.m_dbgStatusMsg.e_stopped.val = TriState.FALSE
      # estopped
      else:
        self.m_dbgStatusMsg.e_stopped.val = TriState.TRUE

      # in estop
      if self.m_dbgStatusMsg.e_stopped.val == TriState.TRUE:
        self.m_dbgStatusMsg.in_error.val = TriState.TRUE
        self.m_dbgStatusMsg.drives_powered.val = TriState.OFF
        self.m_dbgStatusMsg.in_motion.val = TriState.FALSE
        self.m_dbgStatusMsg.current = random.uniform(0.0, 0.4)
      # not in estop
      else:
        # not alarmed
        if random.random() < 0.9:
          self.m_dbgStatusMsg.in_error.val = TriState.FALSE
          self.m_dbgStatusMsg.motion_possible.val = TriState.TRUE
          if random.random() < 0.98:
            self.m_dbgStatusMsg.in_motion.val = TriState.TRUE
          else:
            self.m_dbgStatusMsg.in_motion.val = TriState.FALSE
        # alarmed
        else:
          self.m_dbgStatusMsg.in_error.val = TriState.TRUE
          self.m_dbgStatusMsg.motion_possible.val = TriState.FALSE
          self.m_dbgStatusMsg.in_motion.val = TriState.FALSE
        self.m_dbgStatusMsg.drives_powered.val = TriState.TRUE
        # current
        r = random.uniform(-0.5, 0.5)
        self.m_dbgStatusMsg.current += r
        if self.m_dbgStatusMsg.current < 0.0:
          self.m_dbgStatusMsg.current = 25.0
        elif self.m_dbgStatusMsg.current > 25.0:
          self.m_dbgStatusMsg.current = 25.0
        # charging toggle
        if self.m_dbgStatusMsg.is_charging.val == TriState.TRUE:
          if self.m_dbgStatusMsg.battery > 95.0:
            self.m_dbgStatusMsg.is_charging.val = TriState.FALSE
        else:
          if self.m_dbgStatusMsg.battery < 5.0:
            self.m_dbgStatusMsg.is_charging.val = TriState.TRUE
        # is charging
        if self.m_dbgStatusMsg.is_charging.val == TriState.TRUE:
          r = random.uniform(0.0, 8.0)
        # is not charging
        else:
          r = random.uniform(-8.0, 0.0)
        # battery
        self.m_dbgStatusMsg.battery += r
        if self.m_dbgStatusMsg.battery < 0.0:
          self.m_dbgStatusMsg.battery = 0.0
        elif self.m_dbgStatusMsg.battery > 100.0:
          self.m_dbgStatusMsg.battery = 100.0
        # voltage
        self.m_dbgStatusMsg.voltage = 11.2
        # temperature
        r = random.uniform(-1.0, 1.0)
        self.m_dbgStatusMsg.temp += r
        if self.m_dbgStatusMsg.temp < 0.0:
          self.m_dbgStatusMsg.temp = 0.0
        elif self.m_dbgStatusMsg.temp > 85.0:
          self.m_dbgStatusMsg.temp = 85.0
      # aux enables
      r = random.random()
      if r < 0.7:
        self.m_dbgStatusMsg.aux_batt_en.val = TriState.TRUE
      else:
        self.m_dbgStatusMsg.aux_batt_en.val = TriState.FALSE
      r = random.random()
      if r < 0.7:
        self.m_dbgStatusMsg.aux_5v_en.val = TriState.TRUE
      else:
        self.m_dbgStatusMsg.aux_5v_en.val = TriState.FALSE

      # Robot dyanmics message
      if self.m_dbgStatusMsg.in_motion.val == TriState.TRUE:
        for i in range(0, 4):
          if random.random() < 0.9:
            r = random.uniform(-100.0, 100.0)
          else:
            r = random.uniform(-4000.0, 4000.0)
          self.m_dbgDynamicsMsg.motor_speed[i] += int(r)
      else:
        for i in range(0, 4):
          self.m_dbgDynamicsMsg.motor_speed[i] = 0
      vel = 0.0
      for i in range(0, 4):
        speed = self.m_dbgDynamicsMsg.motor_speed[i]
        self.m_dbgDynamicsMsg.motor_encoder[i] += speed * 16
        vel += speed / (16.0 * 30.0)
        self.m_dbgDynamicsMsg.motor_power_elec[i] = abs(speed)/200.0 * 4.5
      vel = abs(vel/4.0)
      vel = vel * 2.0 * math.pi * 0.065
      self.m_dbgDynamicsMsg.robot_velocity = vel
      self.m_dbgDynamicsMsg.robot_odometer += vel

    #
    # Update
    #
    self.updateRobotStatus(self.m_dbgStatusMsg) 
    self.updateDynamics(self.m_dbgDynamicsMsg) 

    self.m_dbgSeq += 1

  #
  ## \brief Update robot status.
  ##
  ## \param status  Robot status extended message.
  #
  def updateRobotStatus(self, status):
    self.showRobotStatus(status)

  #
  ## \brief Update robot dynamics state.
  ##
  ## \param dynamics  Robot current dynamics state.
  #
  def updateDynamics(self, dynamics):
    self.showDynamics(dynamics)

  #
  ## \brief Show robot status.
  ##
  ## \param status  Robot status extended message.
  #
  def showRobotStatus(self, status):
    if status.mode.val == RobotMode.MANUAL or \
      status.e_stopped.val == TriState.TRUE:
      bNoMoves = True
    else:
      bNoMoves = False

    key = 'mode'
    val = status.mode.val
    if self.m_robotState[key]['raw_val'] != val:
      if val == RobotMode.MANUAL:
        self.m_robotState[key]['widget'].update('amber', 'Manual')
      elif val == RobotMode.AUTO:
        self.m_robotState[key]['widget'].update('green', 'Auto')
      else:
        self.m_robotState[key]['widget'].update('gray', 'Auto')
      self.m_robotState[key]['raw'] = val

      if bNoMoves:
        state = 'disabled'
      else:
        state = 'normal'
      self.updateButtonState(self.m_keysNoMoves, state)

    key = 'motors'
    val = status.drives_powered.val
    if self.m_robotState[key]['raw_val'] != val:
      if val == TriState.ON:
        self.m_robotState[key]['widget'].update('green')
      elif val == TriState.OFF:
        self.m_robotState[key]['widget'].update('gray')
      else:
        self.m_robotState[key]['widget'].update('gray')
      self.m_robotState[key]['raw_val'] = val

    key = 'moving'
    val = status.in_motion.val
    if self.m_robotState[key]['raw_val'] != val:
      if val == TriState.ON:
        self.m_robotState[key]['widget'].update('green')
      elif val == TriState.OFF:
        self.m_robotState[key]['widget'].update('gray')
      else:
        self.m_robotState[key]['widget'].update('gray')
      self.m_robotState[key]['raw_val'] = val

    key = 'watts'
    val = status.voltage * status.current
    self.m_robotState[key]['widget'].update(val)
    self.m_robotState[key]['raw_val'] = val

    key = 'temp'
    val = status.temp
    self.m_robotState[key]['widget'].update(val)
    self.m_robotState[key]['raw_val'] = val

    key = 'alarms'
    val = status.in_error.val
    if self.m_robotState[key]['raw_val'] != val:
      if val == TriState.ON:
        self.m_robotState[key]['widget'].update('red')
      elif val == TriState.OFF:
        self.m_robotState[key]['widget'].update('gray')
      else:
        self.m_robotState[key]['widget'].update('gray')
      self.m_robotState[key]['raw_val'] = val

    key = 'estop'
    val = status.e_stopped.val
    if self.m_robotState[key]['raw_val'] != val:
      if val == TriState.ON:
        self.m_robotState[key]['widget'].update('red')
      elif val == TriState.OFF:
        self.m_robotState[key]['widget'].update('gray')
      else:
        self.m_robotState[key]['widget'].update('gray')
      self.m_robotState[key]['raw_val'] = val

    key = 'battery'
    charge = status.battery
    val = status.is_charging.val
    if val == TriState.TRUE:
      isCharging = True
    else:
      isCharging = False
    if  self.m_robotState[key]['raw_val'][0] != charge or \
        self.m_robotState[key]['raw_val'][1] != isCharging:
      self.m_robotState[key]['widget'].update(charge, isCharging)
      self.m_robotState[key]['raw_val'] = (charge, isCharging)

  #
  ## \brief Show dynamics state.
  ##
  ## \param dynamics  Robot current dynamics state.
  #
  def showDynamics(self, dynamics):
    key = 'velocity'
    val = math.fabs(dynamics.robot_velocity)
    self.m_robotState[key]['widget'].update(val)
    self.m_robotState[key]['raw_val'] = val

    key = 'odometer'
    od  = dynamics.robot_odometer
    self.m_robotState[key]['widget'].update(od)
    self.m_robotState[key]['raw_val'] = od

    key = 'trip_meter'
    val = od - self.m_robotState[key]['raw_val']
    self.m_robotState[key]['widget'].update(val)

    for i in range(0, len(dynamics.name)):
      name = dynamics.name[i]
      if not self.m_subsysState['powertrain'].has_key(name):
        continue

      powertrain = self.m_subsysState['powertrain'][name]

      key = 'watts'
      val = dynamics.motor_power_elec[i]
      powertrain[key]['widget'].update(val)
      powertrain[key]['raw_val'] = val

      key = 'qpps'
      val = dynamics.motor_speed[i]
      powertrain[key]['widget'].update(val)
      powertrain[key]['raw_val'] = val

      key = 'pulses'
      val = dynamics.motor_encoder[i]
      powertrain[key]['widget'].update(val)
      powertrain[key]['raw_val'] = val

  #
  ## \brief Show servo health.
  ##
  ## \param health  Servo health message.
  #
  def showServoHealth(self, health):
    pass

  #
  ## \brief Show information message on status bar.
  ##
  ## \param msg   Info message string.
  #
  def showInfo(self, msg):
    self.m_wStatusBar["state"] = "normal"
    self.m_wStatusBar["fg"]    = fgColors['normal']
    self.m_varStatus.set(msg)
    self.m_wStatusBar["state"] = "readonly"

  #
  ## \brief Show error message on status bar.
  ##
  ## \param msg   Error message string.
  #
  def showError(self, msg):
    self.m_wStatusBar["state"] = "normal"
    self.m_wStatusBar["fg"]    = fgColors['error']
    self.m_varStatus.set(msg)
    self.m_wStatusBar["state"] = "readonly"

  #
  ## \brief Show text on read-only entry.
  ##
  ## \param w     Entry widget.
  ## \param var   Bound entry variable.
  ## \param val   Variable value.
  ## \param fg    Text foreground color.
  #
  def showEntry(self, w, var, val, fg='black'):
    w['state'] = 'normal'
    w['fg']    = fg
    var.set(val)
    w['state'] = 'readonly'

  def toMotorsPowered(self, drives_powered):
    if drives_powered:
      return ("Motors powered", fgColors['normal'])
    else:
      return ("Motors unpowered", fgColors['normal'])

  def toWheelState(self, opstate):
      if opstate == LaelapsOpState.UNCALIBRATED:
        return ("uncalibrated", fgColors['error'])
      elif opstate == LaelapsOpState.CALIBRATING:
        return ("calibrating", fgColors['focus'])
      elif opstate == LaelapsOpState.CALIBRATED:
        return ("calibrated", fgColors['normal'])
      else:
        return (repr(opstate), fgColors['error'])

  def toPercent(self, n):
    return "%6.1f%%" % (n*100.0), fgColors['normal']

  def toDeg(self, rad):
    deg = math.degrees(rad)
    return round100th(deg), fgColors['normal']

  def toVelocity(self, percent):
    return round10th(percent), fgColors['normal']

  def toEffort(self, effort):
    absraw = math.fabs(effort)
    raw    = int(effort)
    if absraw < 900:
      return (raw, fgColors['normal'])
    elif absraw < 1000:
      return (raw, fgColors['warning'])
    else:
      return (raw, fgColors['error'])

  def toTemperature(self, temp):
    if temp >= 75.0:
      color = fgColors['error']
    if temp <= 0.0:
      color = fgColors['error']
    elif temp >= 60.0:
      color = fgColors['warning']
    elif temp <= 10.0:
      color = fgColors['warning']
    else:
      color = fgColors['normal']
    return ("%4.1fC" % (temp), color)

  def toVoltage(self, volts):
    if volts > 14.0:
      color = fgColors['error']
    elif volts < 9.0:
      color = fgColors['error']
    elif volts < 9.6:
      color = fgColors['warning']
    else:
      color = fgColors['normal']
    return ("%3.1fV" % (volts), color)

  def toAlarms(self, alarms):
    return ("TODO", fgColors['error'])
    """
    if alarms == MotorHealth.ALARM_NONE:
      return (alarmStrings[MotorHealth.ALARM_NONE], fgColors['ok'])
    text = ""
    sep  = ""
    for bit in alarmStrings.keys():
      if bit & alarms:
        if len(alarmStrings[bit]) > 0:
          text += sep + alarmStrings[bit]
          sep = ','
    return (text, fgColors['error'])
    """


# ------------------------------------------------------------------------------
# Exception Class usage
# ------------------------------------------------------------------------------

##
## \brief Unit test command-line exception class.
##
## Raise usage excpetion.
##
class usage(Exception):

  ##
  ## \brief Constructor.
  ##
  ## \param msg   Error message string.
  ##
  def __init__(self, msg):
    ## error message attribute
    self.msg = msg


# ------------------------------------------------------------------------------
# Class application
# ------------------------------------------------------------------------------

##
## \brief Laelaps control panel.
##
class application():

  #
  ## \brief Constructor.
  #
  def __init__(self):
    self._Argv0 = __file__
    self.m_win = None

  #
  ## \brief Print usage error.
  ##
  ## \param emsg  Error message string.
  #
  def printUsageErr(self, emsg):
    if emsg:
      print "%s: %s" % (self._Argv0, emsg)
    else:
      print "%s: error" % (self._Argv0)
    print "Try '%s --help' for more information." % (self._Argv0)

  ## \brief Print Command-Line Usage Message.
  def printUsage(self):
    print \
"""
usage: %s [OPTIONS]
       %s --help

Options and arguments:

-h, --help                : Display this help and exit.
"""  % (self._Argv0, self._Argv0)
 
  #
  ## \brief Get command-line options
  ##  
  ## \param argv          Argument list. If not None, then overrides
  ##                      command-line arguments.
  ## \param [out] kwargs  Keyword argument list.  
  ##
  ## \return Parsed keyword arguments.
  #
  def getOptions(self, argv=None, **kwargs):
    if argv is None:
      argv = sys.argv

    self._Argv0 = kwargs.get('argv0', __file__)

    # defaults
    kwargs['debug'] = False # Set to False when finished debugging.

    # parse command-line options
    try:
      opts, args = getopt.getopt(argv[1:], "?h",
          ['help', ''])
    except getopt.error, msg:
      raise usage(msg)
    for opt, optarg in opts:
      if opt in ('-h', '--help', '-?'):
        self.printUsage()
        sys.exit(0)

    #if len(args) < 1:
    #  self.printUsageErr("No input xml file specified")
    #  sys.exit(2)
    #else:
    #  kwargs['filename'] = args[0]

    return kwargs

  #
  ## \brief Initialize interface to laelaps_robot.
  #
  def initRobot(self):
    self.m_win.showInfo("Initializing interface to Laelaps.")

    rospy.init_node("laelaps_panel")

    # subscribe to extended robot status data
    rospy.Subscriber("laelaps_control/robot_status_ex", 
                     RobotStatusExtended, 
                     self.m_win.updateRobotStatus) 

    # subscribe to extended joint state data
    rospy.Subscriber("laelaps_control/dynamics", 
                     Dynamics, 
                     self.m_win.updateDynamics) 

    self.m_win.showInfo("Laelaps interface initialized.")

  #
  ## \brief Run application.
  ##    
  ## \param argv    Optional argument list to override command-line arguments.
  ## \param kwargs  Optional keyword argument list.
  ##
  ## \return Exit code.
  #
  def run(self, argv=None, **kwargs):
  
    # parse command-line options and arguments
    try:
      kwargs = self.getOptions(argv, **kwargs)
    except usage, e:
      print e.msg
      return 2

    # parse application configuration xml file
    xml = ConfigXml()
    config = xml.parse()
    del xml

    # create root 
    root = Tk()

    # create application window
    self.m_win = window(master=root, config=config, **kwargs)

    root.protocol('WM_DELETE_WINDOW', root.destroy)

    root.columnconfigure(0, weight=1)
    root.rowconfigure(0, weight=1)

    # initialize robot interface
    self.initRobot()

    # go for it
    self.m_win.mainloop()

    return 0


# ------------------------------------------------------------------------------
# main
# ------------------------------------------------------------------------------
if __name__ == '__main__':
  app = application();
  sys.exit( app.run() );
