#!/bin/bash

###############################################################################
#
# Package:   RoadNarrows Robotics Laelaps Robotic Mobile Platform ROS Package
#
# Link:      https://github.com/roadnarrows-robotics/laelaps
#
# File: laelaps_stop
#
## \file 
##
## \brief Stop Laelaps movement.
##
## Service type: Stop
##
## A simple command demonstrating the use of rosservice to evoke a service.
##
## \author Robin Knight (robin.knight@roadnarrows.com)
##  
## \par Copyright:
##   (C) 2017.  RoadNarrows LLC.\n
##   (http://www.roadnarrows.com)\n
##   All Rights Reserved
##
# @EulaBegin@
# @EulaEnd@
#
###############################################################################

# The Laelaps service.
svc='/laelaps_control/stop'

rosservice call ${svc}
