#! /usr/bin/env python

###############################################################################
#
# Package:   RoadNarrows Robotics Laelaps Robotic Mobile Platform ROS Package
#
# Link:      https://github.com/roadnarrows-robotics/laelaps
#
# ROS Node:  laelaps_alarms
#
# File: laelaps_alarms
#
## \file 
##
## \brief Stand-alone graphical panel to display Laelaps alarms.
##
## \author Robin Knight (robin.knight@roadnarrows.com)
##  
## \par Copyright:
##   (C) 2017.  RoadNarrows LLC.\n
##   (http://www.roadnarrows.com)\n
##   All Rights Reserved
##
# @EulaBegin@
# @EulaEnd@
#
###############################################################################

from Tkinter import *
from Tkconstants import *
from tkFileDialog import *
import tkFont

import roslib; roslib.load_manifest('laelaps_control')
import rospy

from laelaps_control.AlarmsWin import AlarmsFrame
from laelaps_control.Utils import *

# create root 
root = Tk()

# window title
root.title('laelaps_alarms')

# alarms frame
frame = AlarmsFrame(master=root)
frame.grid(row=0, column=0, padx=5, pady=5)

# on delete callback
def onDelete():
  root.destroy()

# window 'x' button
root.protocol('WM_DELETE_WINDOW', onDelete)

# load image with frame's image loader
iconClose = frame.loadImage('icons/icon_close_32.png')

# close button
k, w = createCompoundButton(root, text='Close', image=iconClose,
            command=onDelete, width=80)
w.grid(row=1, column=0, sticky=N, pady=5)

rospy.init_node("laelaps_alarms")

root.mainloop()
