#! /usr/bin/env python

###############################################################################
#
# Package:   RoadNarrows Robotics Laelaps Robotic Mobile Platform ROS Package
#
# Link:      https://github.com/roadnarrows-robotics/laelaps
#
# ROS Node:  laelaps_twist
#
# File: laelaps_twist
#
## \file 
##
## \brief Stand-alone graphical panel to execute simple twist movements.
##
## \author Robin Knight (robin.knight@roadnarrows.com)
##  
## \par Copyright:
##   (C) 2017.  RoadNarrows LLC.\n
##   (http://www.roadnarrows.com)\n
##   All Rights Reserved
##
# @EulaBegin@
# @EulaEnd@
#
###############################################################################

from Tkinter import *
from Tkconstants import *
from tkFileDialog import *
import tkFont

import roslib; roslib.load_manifest('laelaps_control')
import rospy

from laelaps_control.TwistMoveWin import TwistMoveFrame

# create root 
root = Tk()

root.title('laelaps_ranges')

# alarams frame
frame = TwistMoveFrame(master=root)
frame.grid(row=0, column=0, padx=5, pady=5)

# on delete callback
def onDelete():
  frame.cleanup()
  root.destroy()

# window 'x' button
root.protocol("WM_DELETE_WINDOW", onDelete)

# close button
w = Button(root, width=10, text='Close', command=onDelete, anchor=CENTER)
w.grid(row=1, column=0, sticky=N, pady=5)

rospy.init_node("laelaps_twist")

root.mainloop()
