#!/bin/bash

###############################################################################
#
# Package:   RoadNarrows Robotics Laelaps Robotic Mobile Platform ROS Package
#
# Link:      https://github.com/roadnarrows-robotics/laelaps
#
# ROS Node:  usb_cam services, web_video_server node
#
# File: laelaps_cam
#
## \file 
##
## \brief Launch Web video server on target.
##
## \author Robin Knight (robin.knight@roadnarrows.com)
##  
## \par Copyright:
##   (C) 2017.  RoadNarrows LLC.\n
##   (http://www.roadnarrows.com)\n
##   All Rights Reserved
##
# @EulaBegin@
# @EulaEnd@
#
###############################################################################

video_device=$(readlink /dev/fcam)

# 
# Front camera
#
if [ -n "${video_device}" ]
then
  video_device="/dev/"$(basename ${video_device})
  window_name="Laelaps Front Camera"
else
  video_device=${video_device:-/dev/video0}
  window_name="Laelaps Camera"
fi

roslaunch laelaps_launch web_video_server.launch video_device:=${video_device} &

roslaunchpid=$!

wait ${roslaunchpid}
