#!/usr/bin/env python

import rospy

from laelaps_control.msg import SpeedCmd
from hid.msg import Controller360State

def callback(data,pub):
  mot_id =[1, 2, 3, 4]
  speed = [(data.left_joy_y+data.left_joy_x)/32768.0, 
           (data.left_joy_x-data.left_joy_y)/32768.0)]
  pub.publish(SpeedCmd(devName, mot_id, speed))
  rospy.loginfo(rospy.get_name() + ": Received Command")

if __name__='__main__':
  rospy.init_node('set_speed', anonymous=True)
  pub = rospy.Publisher('/roboteq/speed_command', SpeedCmd)
  rospy.Subscriber("xbox_360/controller_360_state", Controller360State, 
                  callback, pub)

  rospy.spin()

