## All icons in Laelaps package.
__all__ = [
  'LaelapsAlarmsIcon.png',
  'LaelapsPanelIcon.png',
  'icon_alarm.png',
  'icon_bot_back.png',
  'icon_bot_brake.png',
  'icon_bot_forward.png',
  'icon_bot_spin_left.png',
  'icon_bot_spin_right.png',
  'icon_estop.png',
  'icon_estop_reset.png',
  'icon_exit.png',
  'icon_info.png',
  'icon_laelaps_logo.png',
  'icon_led_dark_16.png',
  'icon_led_green_16.png',
  'icon_led_red_16.png',
  'icon_led_yellow_16.png',
  'icon_pause.png',
  'icon_settings.png',
]
